 version: "3.3"

 services:
   api-usuarios:
     build: ./api-usuarios
     image: mark2024/api-usuarios
     ports:
       - 8001:8001
   api-productos:
     build: ./api-productos
     image: mark2024/api-productos
     ports:
       - 8082:8002
   api-pedidos:
     build: ./api-pedidos
     image: mark2024/api-pedidos
     ports:
       - 8003:8003     
